<Project Sdk="Godot.NET.Sdk/4.5.1" InitialTargets="CheckDependencyPaths">
    <Import Project=".\Sts2PathDiscovery.props"/>
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <AssemblyName>BantersTweaks</AssemblyName>
        <RootNamespace>SpireGPS</RootNamespace>
        <Version>0.1.0</Version>
        <ImplicitUsings>true</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <NoWarn>$(NoWarn);MSB3270</NoWarn>
    </PropertyGroup>

    <ItemGroup Condition="Exists('$(Sts2DataDir)')">
        <Reference Include="0Harmony">
            <HintPath>$(Sts2DataDir)/0Harmony.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="sts2">
            <HintPath>$(Sts2DataDir)/sts2.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>

    <Target Name="CheckDependencyPaths">
        <Error Text="Slay the Spire 2 data not found at path '$(Sts2DataDir)'" Condition="'$(Sts2DataDir)' == '' or !Exists('$(Sts2DataDir)')" />
    </Target>

    <ItemGroup>
        <ModAsset Include="Assets\**\*" />
    </ItemGroup>

    <Target Name="CopyToModsFolderOnBuild" AfterTargets="PostBuildEvent" Condition="'$(InstallToGame)' == 'true'">
        <RemoveDir Directories="$(ModsPath)SpireGPS/" Condition="Exists('$(ModsPath)SpireGPS/')" />
        <RemoveDir Directories="$(ModsPath)$(AssemblyName)/" Condition="Exists('$(ModsPath)$(AssemblyName)/')" />
        <MakeDir Directories="$(ModsPath)$(AssemblyName)/" />
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ModsPath)$(AssemblyName)/" />
        <Copy SourceFiles="$(AssemblyName).json" DestinationFolder="$(ModsPath)$(AssemblyName)/" />
        <Copy SourceFiles="THIRD_PARTY_NOTICES.md" DestinationFolder="$(ModsPath)$(AssemblyName)/" Condition="Exists('THIRD_PARTY_NOTICES.md')" />
        <Copy
            SourceFiles="@(ModAsset)"
            DestinationFiles="@(ModAsset->'$(ModsPath)$(AssemblyName)/%(Identity)')"
            SkipUnchangedFiles="true"
            Condition="'@(ModAsset)' != ''" />
        <Copy SourceFiles="$(TargetDir)$(TargetName).pdb" DestinationFolder="$(ModsPath)$(AssemblyName)/" Condition="Exists('$(TargetDir)$(TargetName).pdb')" />
    </Target>
</Project>
